### ISSUE TITLE
Update required checks

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/web-libraries#158]
**What needs to be done? Why does it need to be done?**
The following CI checks should be required for a PR merge, in addition to any other checks that are already required: 
- Build auth package
- Lint auth package
- Test auth package

**Additional context**
n/a

**Comment by phenggeler** [comment]
@macfarlandian - done!

![image](https://github.com/Recidiviz/web-libraries/assets/10621768/44244d39-64e3-44da-ad0c-a83169e2484c)
