### ISSUE TITLE
Security Alert - Severity: Medium

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/web-libraries#82]
---
due: 2022-05-03
--- 

**What needs to be done? Why does it need to be done?**
Please upgrade the following packages or dismiss the Dependabot alert.

`postcss`
`ansi-regex`
`nth-check`
`glob-parent`
`browserslist`
`node-fetch`

**Additional context**
Add any other context about the task here.

**Comment by macfarlandian** [comment]
these are all build tools, no application vulnerability results from this. They have all been dismissed.
