### ISSUE TITLE
Address vulnerabilities in `web-libraries`

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/web-libraries#95]
---
due: 2022-05-08
--- 
    
Please address the following vulnerabilities in this repository:

[minimist (npm)](https://github.com/Recidiviz/web-libraries/security/dependabot)
[ansi-regex (npm)](https://github.com/Recidiviz/web-libraries/security/dependabot)

**Comment by phenggeler** [comment]
@phenggeler - label applied: Due this month.

**Comment by phenggeler** [comment]
@macfarlandian - just bumping this ticket. It will be due in the next month. FYI

**Comment by phenggeler** [comment]
@phenggeler - label applied: Due this week.

**Comment by macfarlandian** [comment]
`minimist` has been addressed, and according to Dependabot there is no update needed for `ansi-regex` so I'm going to dismiss those. There doesn't seem to be any real vulnerability associated with `ansi-regex` in this package anyway.

**Comment by phenggeler** [comment]
Thanks @macfarlandian
